import { Inter } from "next/font/google";
import { ApolloClientProvider } from "@/ApolloProvider/ApolloProvider";
import Layout from "./components/Layout/Layout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecomerce Montero",
  description: "Generated by Stripe",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApolloClientProvider>
          <Layout>{children}</Layout>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
