import { Inter } from "next/font/google";
import { ApolloClientProvider } from "./ApolloProvider/ApolloProvider.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecomerce Montero",
  description: "Generated by Stripe",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApolloClientProvider>{children}</ApolloClientProvider>
      </body>
    </html>
  );
}
