export const PRODUCT_INCREMENT_COUNTER = "PRODUCT_INCREMENT_COUNTER";
export const PRODUCT_DECREMENT_COUNTER = "PRODUCT_DECREMENT_COUNTER";
export const PRODUCTS_SELECTED_BY_CUSTOMER = "PRODUCTS_SELECTED_BY_CUSTOMER";
export const PRODUCT_RESET_COUNTER = "PRODUCT_RESET_COUNTER";
export const PRE_PRODUCT_OBJECT = "PRE_PRODUCT_OBJECT";
