export const producto = [
  {
    id: 1,
    name: "Pudin",
    status: "NEW",
    description: " Sabor a Vainilla y Canela",
    price: 7,
    existence: 20,
    image: "/pudin.png",
    alt: "Pudin",
  },
  {
    id: 2,
    name: "Espagueti",
    status: "NEW",
    description: " Trigo Seleccionado",
    price: 4,
    existence: 50,
    image: "/Espaguetis.png",
    alt: "Espaguetis",
  },
  {
    id: 3,
    name: "Bolsa de Pollo",
    status: "NEW",
    description: " Fresco y libre de Biotecnologia",
    price: 8,
    existence: 30,
    image: "/Pollo.png",
    alt: "Bolsa de Pollo",
  },
  {
    id: 4,
    name: "Aceite de Comer",
    status: "NEW",
    description: " Frasco de 1 Litro",
    price: 10,
    existence: 35,
    image: "/aceite.png",
    alt: "Aceite de Comer",
  },
  {
    id: 5,
    name: "Canela ",
    status: "NEW",
    description: " Pliegues y polvo ",
    price: 5,
    existence: 24,
    image: "/canela.png",
    alt: "canela",
  },
  {
    id: 6,
    name: "Salchichas ",
    status: "NEW",
    description: " Paquete de 2KG ",
    price: 10,
    existence: 15,
    image: "/salchichas.png",
    alt: "salchichas",
  },
  {
    id: 7,
    name: "Mantequilla ",
    status: "NEW",
    description: " Con sal, Leche pura ",
    price: 11,
    existence: 25,
    image: "/mantequilla.png",
    alt: "mantequilla",
  },
  {
    id: 8,
    name: "Sorbetos de Chocolate ",
    status: "NEW",
    description: " 142 gramos ",
    price: 4.5,
    existence: 100,
    image: "/sorbetos.png",
    alt: "sorbetos",
  },
];
